-- AlterTable
ALTER TABLE `Character` MODIFY `charClass` ENUM('BARBARIAN', 'ROUGE', 'SORCERER', 'WIZARD', 'ARTIFICER', 'BARD', 'CLERIC', 'DRUID', 'MONK', 'WARLOCK', 'FIGHTER', 'PALADIN', 'RANGER') NOT NULL;
